name: TrainingPeaks to Intervals Sync

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Env Configuration File
        run: |
          echo "TP_USERNAME=${{ secrets.TP_USERNAME }}" >> .env
          echo "TP_PASSWORD=${{ secrets.TP_PASSWORD }}" >> .env
          echo "INTERVALS_ATHLETE_ID=${{ secrets.INTERVALS_ATHLETE_ID }}" >> .env
          echo "INTERVALS_API_KEY=${{ secrets.INTERVALS_API_KEY }}" >> .env
          echo "DAYS_FORWARD=2" >> .env

      - name: Run Sync via Docker Env File
        run: |
          docker run --rm --env-file .env ghcr.io/freekode/tp2intervals:latest
